/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseSvg: typeof import('./components/Base/BaseSvg.vue')['default']
    MainPage: typeof import('./pages/MainPage.vue')['default']
    NftInfo: typeof import('./components/Reusable/NftInfo.vue')['default']
    PictureComponent: typeof import('./components/Base/PictureComponent.vue')['default']
    SvgManager: typeof import('./components/Base/SvgManager.vue')['default']
    SwiperNft: typeof import('./components/Reusable/SwiperNft.vue')['default']
    SwiperUser: typeof import('./components/Reusable/SwiperUser.vue')['default']
    TheCard: typeof import('./components/Base/TheCard.vue')['default']
    TheHeader: typeof import('./components/Reusable/TheHeader.vue')['default']
    UIButton: typeof import('./components/UI/UIButton.vue')['default']
    UISmallButton: typeof import('./components/UI/UISmallButton.vue')['default']
    UserCard: typeof import('./components/Reusable/UserCard.vue')['default']
    UserInfo: typeof import('./components/Reusable/UserInfo.vue')['default']
  }
}
