/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseSvg: typeof import('./components/base/BaseSvg.vue')['default']
    Header: typeof import('./components/reusable/Header.vue')['default']
    MainSlider: typeof import('./components/partials/pages/main/MainSlider.vue')['default']
    SvgManager: typeof import('./components/base/SvgManager.vue')['default']
  }
}
